name: cooperation_platform_flutter
description: "تطبيق منصة التعاون على الخير - تطبيق Flutter لتسهيل العمل الخيري والتطوعي"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI Components
  cupertino_icons: ^1.0.8
  material_design_icons_flutter: ^7.0.7296
  
  # State Management
  provider: ^6.1.2
  
  # Navigation
  go_router: ^14.2.7
  
  # HTTP & API
  http: ^1.2.2
  dio: ^5.7.0
  
  # Local Storage
  shared_preferences: ^2.3.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # Authentication
  firebase_auth: ^5.3.1
  firebase_core: ^3.6.0
  google_sign_in: ^6.2.1
  
  # Image Handling
  image_picker: ^1.1.2
  cached_network_image: ^3.4.1
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.3.1
  permission_handler: ^11.3.1
  
  # Charts & Analytics
  fl_chart: ^0.69.0
  
  # File Handling
  file_picker: ^8.1.2
  path_provider: ^2.1.4
  
  # Notifications
  flutter_local_notifications: ^17.2.3
  
  # Animations
  lottie: ^3.1.2
  
  # Form Validation
  form_field_validator: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/
  
  # Fonts
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf
        - asset: assets/fonts/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/Cairo-Light.ttf
          weight: 300
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal-Regular.ttf
        - asset: assets/fonts/Tajawal-Bold.ttf
          weight: 700
        - asset: assets/fonts/Tajawal-Light.ttf
          weight: 300

flutter_intl:
  enabled: true
  arb_dir: lib/l10n
  output_dir: lib/generated
  main_locale: ar
